# Generated by Django 4.2.2 on 2023-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_books.jpg', upload_to='profile_images', verbose_name='Аватарка'),
        ),
    ]
