# Generated by Django 4.2.2 on 2023-07-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_options_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 16, 2, 7, 680192, tzinfo=datetime.timezone.utc), verbose_name='Дата внесения в базу'),
        ),
    ]
