# Generated by Django 4.2.2 on 2023-07-15 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='default_book.png', upload_to='books_images', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 4, 57, 28, 147265, tzinfo=datetime.timezone.utc), verbose_name='Дата внесения в базу'),
        ),
    ]
