# Generated by Django 4.2.2 on 2023-07-15 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_photo_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 16, 37, 45, 584234, tzinfo=datetime.timezone.utc), verbose_name='Дата внесения в базу'),
        ),
    ]
